language: go

go:
- 1.6

sudo: required

services:
  - docker

# The default script is go test -v ./... which will test everything
# in the vendor directory. We don't need to test all dependent packages.
# Only testing this project.
script:
- GO15VENDOREXPERIMENT=1 make travis-ci
